### ISSUE TITLE
ModuleNotFoundError: No module named 'pixelengine' in python while converting the phiips isyntax format file into OME-TIFF.

### ISSUE THREAD

**Issue by Yadav420dilip** [glencoesoftware/isyntax2raw#11]
**ModuleNotFoundError: No module named 'pixelengine' in python while converting the phiips isyntax format file into OME-TIFF or TIFF.**

By following this documentation https://www.glencoesoftware.com/blog/2019/12/09/converting-whole-slide-images-to-OME-TIFF.html#footnotes

I used python 3.6 in ubuntu 18.04.

First I download and install the [philips sdk](https://www.philips.co.in/healthcare/sites/pathology/release-press/20190806-philips-pathology-sdk-now-available-to-software-developers-and-scientists) as per given instruction in documentation.

After that I downloaded [isyntax2raw](https://github.com/glencoesoftware/isyntax2raw) and install it.

After executing the following  command in terminal

**$ isyntax2raw write_tiles 20200207_140740.isyntax  /home/dilip/new_image.tiff**

The error comes

**Traceback** (most recent call last): File "/home/dilip/anaconda3/envs/myenv/bin/isyntax2raw", line 11, in load_entry_point('isyntax2raw==0.0.0', 'console_scripts', 'isyntax2raw')() File "/home/dilip/anaconda3/envs/myenv/lib/python3.6/site-packages/pkg_resources/init.py", line 490, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File "/home/dilip/anaconda3/envs/myenv/lib/python3.6/site-packages/pkg_resources/init.py", line 2859, in load_entry_point return ep.load() File "/home/dilip/anaconda3/envs/myenv/lib/python3.6/site-packages/pkg_resources/init.py", line 2450, in load return self.resolve() File "/home/dilip/anaconda3/envs/myenv/lib/python3.6/site-packages/pkg_resources/init.py", line 2456, in resolve module = import(self.module_name, fromlist=['name'], level=0) File "/home/dilip/anaconda3/envs/myenv/lib/python3.6/site-packages/isyntax2raw-0.0.0-py3.6.egg/isyntax2raw/init.py", line 15, in ModuleNotFoundError: No module named **'pixelengine'**

**Comment by melissalinkert** [comment]
That error indicates that the Philips SDK (```pixelengine```) was not installed correctly.  It looks like you are using Anaconda, in which case the ```conda list pixelengine``` command should tell you which version of the SDK (if any) is installed.

**Comment by Yadav420dilip** [comment]
> That error indicates that the Philips SDK (`pixelengine`) was not installed correctly. It looks like you are using Anaconda, in which case the `conda list pixelengine` command should tell you which version of the SDK (if any) is installed.

Thanks it worked.

**Comment by ghadjigeorghiou** [comment]
@Yadav420dilip could you please explain or share any resources on how to install the SDK in anaconda?

**Comment by Yadav420dilip** [comment]
I installed into my ubuntu 20.04.
Install anaconda after the create new conda environment and activate the environment and follow the following steps

At the Open Pathology portal, select Pathology SDK.
► Download the required Ubuntu installer package to your system.
► In the Ubuntu command prompt, enter chmod 777 InstallPathologySDK.sh to go to the
package directory and change the permission for InstallPathologySDK.sh.
► Go the package directory and enter ./InstallPathologySDK.sh py3.
⇨ After successful installation, a confirmation message is shown.

**Comment by ghadjigeorghiou** [comment]
It worked. Thanks!

**Comment by pathdata** [comment]
> I installed into my ubuntu 20.04. Install anaconda after the create new conda environment and activate the environment and follow the following steps
> 
> At the Open Pathology portal, select Pathology SDK ► Download the required Ubuntu installer package to your system [https://www.openpathology.philips.com/pathologysdk/] ► In the Ubuntu command prompt, enter chmod 777 InstallPathologySDK.sh to go to the package directory and change the permission for InstallPathologySDK.sh. ► Go the package directory and enter ./InstallPathologySDK.sh py3. ⇨ After successful installation, a confirmation message is shown.

I did all the above and I have the SDK-2.0 installed. But the No module found import pixelengine error still appears.

**Comment by Yadav420dilip** [comment]
Might be sdk is not installed properly. installed sdk correctly

**Comment by JoyLinWQ** [comment]
> > I installed into my ubuntu 20.04. Install anaconda after the create new conda environment and activate the environment and follow the following steps
> > At the Open Pathology portal, select Pathology SDK ► Download the required Ubuntu installer package to your system [https://www.openpathology.philips.com/pathologysdk/] ► In the Ubuntu command prompt, enter chmod 777 InstallPathologySDK.sh to go to the package directory and change the permission for InstallPathologySDK.sh. ► Go the package directory and enter ./InstallPathologySDK.sh py3. ⇨ After successful installation, a confirmation message is shown.
> 
> I did all the above and I have the SDK-2.0 installed. But the No module found import pixelengine error still appears.

try ubuntu 18.04?
