### ISSUE TITLE
SDK Access

### ISSUE THREAD

**Issue by jdenholm** [glencoesoftware/isyntax2raw#34]
The link to the Philips open pathology portal seems to be dead, and if one goes to the Philips knowledge centre to download  the SDK, one finds it can no longer be downloaded on Ubuntu (or probably any linux flavour) or mac os (even though this used to be possible). I guess this means people in these camps can no longer use this package?

Is it possible to include the SDK in this repo, or for someone to get in touch with Philips and request the website is fixed? It has been like this for (at least) several months.

I would be super-grateful if the SDK becomes available again, or if someone could advise, so we can use the code in this very useful repo.

Thank you!

**Comment by chris-allan** [comment]
As much as we would like to offer the Philips SDK for download its licensing terms explicitly forbid redistribution. Through some of our partners we have been in active dialogue with Philips for some time trying to get the current scenario resolved; unfortunately it is out of our hands. I would recommend that you contact Philips directly with your concerns..

See also #33.

**Comment by chris-allan** [comment]
Contact details and the full Philips SDK site maintenance bulletin:

>The Philips Open Pathology Portal website is undergoing maintenance.
>
>Meanwhile customers can download the Philips Software Development Kit and Pathology Image File Viewer from Incenter (https://philips.mizecx.com/login.html), using the Guest User Login to access the links to the software.
>
>For support please send an email to `"Customer Services" <DCP_SDK_CallCenter@philips.com>`, with the subject 'I need support / have a question'
>
>Please include the following details to help us respond efficiently to your query:
>
>Your Name:
>
>Email address: (customer contact if reporting on behalf of one)
>
>Contact telephone number (optional):
>
>Product (Software Development Kit/Pathology Image File Viewer/Other):
>
>Brief Description:
